version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: postgres_hp
    environment:
      POSTGRES_DB: harry_potter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:7
    container_name: mongo_hp
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: harry_potter
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  neo4j:
    image: neo4j:5.15
    container_name: neo4j_hp
    environment:
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_dbms_default__database: harrypotter
      NEO4J_dbms_databases_read__only: false
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4jdata:/data
volumes:
  pgdata:
  mongodata:
  neo4jdata:
