version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: postgres_hp
    environment:
      POSTGRES_DB: harry_potter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      LANG: C.UTF-8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
